[oauth]
redirect_url = "/endpoints/"

[server]
port = 3321
debug = true
host = "0.0.0.0"
threaded=false
threads=4

[users]
local = true
file_path = "<data_path>/users.json"
url = ""
web_config = "<config_path>/web.json"

[endpoints]
path = "<config_path>/endpoints.json"

[data]
file_structure = "<data_path>/local/{}/{}.csv"
path = "<data_path>/local/"
local = true
csv_sep = ","
time_pattern = "%Y-%m-%dT%H:%M:%SZ"
data_warn = true
[actions]
file_path = "<data_path>/actions.json"
[paths]
config_path = "config"
data_path = "data"

[options]
to_std_out = true
production = false

[thread]
time_out = 0.5
auto_start = false