[oauth]
redirect_url = "/endpoints/"

[server]
port = 3321
debug = true
host = "0.0.0.0"
threaded=false
threads=4

[users]
local = true
file_path = "<data_path>/users.json"
url = ""
web_config = "<config_path>/web.json"

[endpoints]
path = "<config_path>/endpoints.json"

[data]
file_structure = "<data_path>/{uid}/{endpoint}/{day}.csv"

[paths]
config_path = "config"
data_path = "data"

[options]
to_std_out = true

